spring:
  application:
    name: gateway-service
server:
  port: 7770

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/registry/eureka
    fetch-registry: true
    register-with-eureka: false
  server:
    host: localhost
    port: 8761

ribbon:
  restclient:
    enabled: true
  eureka:
    enabled: true

zuul:
  ignored-services: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    products-service:
      path: /products-service/**
      serviceId: products-service
      stripPrefix: false
      sensitiveHeaders:

logging:
  level:
    ROOT: INFO
